#
# travis (http://travis-ci.org/)
#  build description 
#   for portz (https://github.com/zbigg/portz)
#

language: cpp

branches:
  only:
    - master

before_script:
  - env
  - autoreconf --version
  - find . -type f | xargs ls -ald
  - autoreconf -i
  - autoconf
  - ./configure

script:
  - make
  - make distcheck

